"""generate companies

Revision ID: 2f50816e4c38
Revises: 70223910c58b
Create Date: 2025-09-24 15:17:29.324155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f50816e4c38'
down_revision: Union[str, Sequence[str], None] = '70223910c58b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('description', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('mode', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('rating', sa.Integer(), nullable=True))
    op.drop_column('companies', 'website')
    op.drop_column('companies', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('companies', 'rating')
    op.drop_column('companies', 'mode')
    op.drop_column('companies', 'description')
    # ### end Alembic commands ###
